apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: sabnzbd-n-m21
        envSlug: dev
        secretsPath: "/"
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: sabnzbd

  managedKubeSecretReferences:
    - secretName: sabnzbd-secrets
      secretNamespace: sabnzbd
      creationPolicy: "Owner"
