apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-restic-config
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: sabnzbd-n-m21
        envSlug: dev
        secretsPath: "/restic"
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: sabnzbd

  managedKubeSecretReferences:
    - secretName: restic-config
      secretNamespace: sabnzbd
      secretType: Opaque
      creationPolicy: "Owner"
