apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-restic-config
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: jellyfin-rgm0
        envSlug: dev
        secretsPath: "/restic"
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: jellyfin

  managedKubeSecretReferences:
    - secretName: restic-config
      secretNamespace: jellyfin
      secretType: Opaque
      creationPolicy: "Owner"
