- op: add
  path: /cluster/apiServer
  value:
    extraArgs:
      feature-gates: UserNamespacesSupport=true,UserNamespacesPodSecurityStandards=true
- op: add
  path: /machine/sysctls
  value:
    user.max_user_namespaces: "11255"
- op: add
  path: /machine/kubelet/extraConfig
  value:
    featureGates:
      UserNamespacesSupport: true
      UserNamespacesPodSecurityStandards: true
