apiVersion: v2
name: democratic-csi
version: 1.0.0
dependencies:
  - name: democratic-csi
    alias: node-man
    version: 0.15.0
    repository: https://democratic-csi.github.io/charts/
  - name: democratic-csi
    alias: fn-iscsi
    version: 0.15.0
    repository: https://democratic-csi.github.io/charts/
